title: Sebastian Wiewióra - GitHub Portfolio
description: Welcome to my portfolio. Here you can find my articles, repositories and code snippets.
author: Sebastian Wiewiora
github: https://github.com/swiewiora
about: Software Engineer
# disqus_shortname: portfolio
# google_analytics: UA-XXXXXXXX-Y
# avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/swiewiora/"
    - icon: fa-github
      link: "https://github.com/swiewiora"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: Articles
      url: /category/all
    - text: Projects
      url: /projects
    - text: Gists
      url: https://gist.github.com/swiewiora
      

url: "https://swiewiora.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
