version: '3'
services:
    jekyll:
        image: jekyll/jekyll:pages
        command: jekyll serve --watch --force_polling --livereload
        ports:
            - 4000:4000
            - 35729:35729
        volumes:
            - .:/srv/jekyll